# Numpy

This is a short introduction to Numpy. 

First we import the modules needed for this introduction and abreviate them with the `as` feature of the import statement

In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

Now we showcase some features of Numpy. 

## Float Range

`arange()` is like `range()`, but for floating-point numbers. 

In [2]:
X = np.arange(0.2,1,.1)

In [3]:
print (X)

[ 0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


We use this function to generate parameter space that can then be iterated on.  

In [4]:
P = 10.0 ** np.arange(-7,1,1)

print (P)

[  1.00000000e-07   1.00000000e-06   1.00000000e-05   1.00000000e-04
   1.00000000e-03   1.00000000e-02   1.00000000e-01   1.00000000e+00]


In [5]:
for x,p in zip(X,P):
    print ('%f, %f' % (x, p))

0.200000, 0.000000
0.300000, 0.000001
0.400000, 0.000010
0.500000, 0.000100
0.600000, 0.001000
0.700000, 0.010000
0.800000, 0.100000
0.900000, 1.000000


## Arrays

To create one dimensional arrays you use 

In [6]:
a = np.array([1, 2, 3])   

To check some properties you can use the following

In [7]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [8]:
print(a.shape)            # Prints "(3,)"

(3,)


The shape indicates that in the first dimension, there are 3 elements. To print the actual values you can use 

In [9]:
print(a)                  # Prints the values of the array
print(a[0], a[1], a[2])   # Prints "1 2 3"

[1 2 3]
1 2 3


To change values you can use the index of the element or use any other python method to do so. IN our example we change the first element to `42`

In [10]:
a[0] = 42                 
print(a)                  

[42  2  3]


To create more dimensional arrays you use 

In [11]:
b = np.array([[1,2,3],[4,5,6]])    # Create a 2 dimensional array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


## Array Operations

Let us first create some arrays with a predefined datatype

In [12]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [13]:
print (x)

[[ 1.  2.]
 [ 3.  4.]]


In [14]:
print(y)

[[ 5.  6.]
 [ 7.  8.]]


To add the numbers use

In [15]:
print(x+y)

[[  6.   8.]
 [ 10.  12.]]


Other functions such as `-`, `*`, `/` behave as expected using elementwise oerations: 

In [16]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [17]:
print(x*y)

[[  5.  12.]
 [ 21.  32.]]


In [18]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


To apply functions such as 'sin' make sure you use the function provided by the numpy package such as `np.sin`. The list of functions is included in the manual at 
* https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [19]:
print (np.sin(x))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [20]:
print (np.sum(x))

10.0


Computations can also be applied to columns and rows

In [21]:
print(np.sum(x, axis=0)) # sum of each column
print(np.sum(x, axis=1)) # sum of each row

[ 4.  6.]
[ 3.  7.]


## Linear Algebra

Linear algebra methods are also provided.

In [22]:
from numpy import linalg 

A = np.diag((1,2,3))

w,v = linalg.eig(A)

print ('w =', w)
print ('v =', v)

w = [ 1.  2.  3.]
v = [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Resources

* https://docs.scipy.org/doc/numpy/
* http://cs231n.github.io/python-numpy-tutorial/#numpy
